### ISSUE TITLE
Use a i2c IR contactless temperature sensor

### ISSUE THREAD

**Issue by psych0d0g** [psych0d0g/ESP8266_FishTank#5]
Benefits:

 *   No electronics in the Fishtank
 *   No electric interference for the sensor (the NTC Wires are affected for example by the usually used cathode light in fishtanks)

**Comment by BernhardQ** [comment]
Good reason
I use the same sensor chip on an other board.

**Comment by psych0d0g** [comment]
sensor ordered, coding will be done once it arrived

**Comment by psych0d0g** [comment]
implemented and working
